### ISSUE TITLE
[issue] problems typing

### ISSUE THREAD

**Issue by HitaloSama** [vhqtvn/VHSCode-Android#12]
I can't delete text in the VS Code editor, i also have problems with deleting text in other areas of the interface (as in module search) where every 20 taps in the delete button it just deletes a letter, in the VS Code terminal when trying to delete words they duplicate (example: apt install pythonpythonpythonpythonpythonpython) and after numerous duplications begin to be deleted and also in the terminal is being used automatically uppercase letter which is quite annoying because I always have to put in lowercase letters to type commands.

**Comment by vhqtvn** [comment]
1. The delete key problem is well-known for virtual keyboard, because they're not reporting the keycode for each key, every key will report key code of 229 until the word is composed and an "input" even is fired with the result string. I implemented a hacky way to get correct keycode for hard keyboard only. Another solution is to use Hacker's Keyboard: https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en
2. I think the uppercase problem is related to your keyboard too, which keyboard are you using?

**Comment by HitaloSama** [comment]
@vhqtvn I use SwiftKey

**Comment by vhqtvn** [comment]
Is it working now by using Hacker's Keyboard?

**Comment by HitaloSama** [comment]
@vhqtvn yes, too bad he's too ugly 😂

**Comment by HitaloSama** [comment]
Closing this issue because it is related to a limitation of some keyboards, I am currently using hackers keyboard only in VHS Code because SwiftKey (keyboard i normally use) does not work correctly in VHS Code.

**Comment by unixandria-xda** [comment]
It's kinda ridiculous that you have to use a completely outdated, janky, and lackd every feature besides typing
